// API CALLS
export const REQUEST_LOAD_CATALOG = 'REQUEST_LOAD_CATALOG';
export const RESPONSE_LOAD_CATALOG_SUCCESS = 'RESPONSE_LOAD_CATALOG_SUCCESS';
export const RESPONSE_LOAD_CATALOG_FAILURE = 'RESPONSE_LOAD_CATALOG_FAILURE';

// common
export const SHOW_TOAST = 'SHOW_TOAST';