// DEVICES
export const ADD_NEW_DEVICE = 'ADD_NEW_DEVICE';
export const REMOVE_DEVICE = 'REMOVE_DEVICE';

// API
export const RESPONSE_GET_PICS_LIST_SUCCESS = 'RESPONSE_GET_PICS_LIST_SUCCESS';
export const RESPONSE_GET_PICS_LIST_FAILURE = 'RESPONSE_GET_PICS_LIST_FAILURE';

// common
export const INIT = 'INIT';
export const SHOW_TOAST = 'SHOW_TOAST';